name: Deploy Fullstack App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configure AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3️⃣ Deploy Backend via SSH
      - name: Deploy backend to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.BACKEND_EC2_KEY }}
          script: |
            # Create directory if missing
            mkdir -p /opt/backend/app/backend
            cd /opt/backend/app

            # Clone repo if not exists
            if [ ! -d "backend" ]; then
              git clone https://github.com/anasmak04/aws-fullstack-app-ci-cd backend
            fi

            cd backend

            # Pull latest code
            git pull

            # Install dependencies
            npm install

            # Start or restart app with PM2
            pm2 start app.js --name backend-api || pm2 restart backend-api
            pm2 save

      # 4️⃣ Deploy Frontend to S3
      - name: Deploy frontend to S3
        run: |
          aws s3 sync ./webapp/ s3://client-app-644993686940-us-east-1/ --delete
          aws s3 cp ./webapp/index.html s3://client-app-644993686940-us-east-1/index.html
